// Generated by CoffeeScript 1.7.1
(function() {
  var canvas, canvas_height, canvas_width, ctx, draw_scenery, frame, keys_down;

  canvas = null;

  ctx = null;

  frame = 0;

  canvas_width = 640;

  canvas_height = 480;

  keys_down = {};

  draw_scenery = function() {
    ctx.fillStyle = 'black';
    ctx.fillRect(0, 0, canvas_width, canvas_height);
    return null;
  };

  $(document).ready(function() {
    var animloop;
    canvas = $('#canvas')[0];
    ctx = canvas.getContext('2d');
    $(document).keydown(function(evt) {
      keys_down[evt.which] = true;
      return null;
    });
    $(document).keyup(function(evt) {
      delete keys_down[evt.which];
      return null;
    });
    window.requestAnimFrame = (function() {
      return window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function(callback) {
        return window.setTimeout(callback, 1000 / 60);
      };
    })();
    return (animloop = function() {
      requestAnimFrame(animloop);
      if ($('#running')[0].checked) {
        frame++;
        draw_scenery();
        $('#debug')[0].innerHTML = "Frame " + frame;
      }
      return null;
    })();
  });

}).call(this);
